---
- name: Get Interface Profile from switch policy leaf
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../../ACI_Deployment_Template.xlsx
    no_log: True

  - name: Get interface selector profile to switch policy leaf profile
    aci_interface_selector_to_switch_policy_leaf_profile:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      interface_selector: "{{ item.Interface_Profile }}"
      leaf_profile: "{{ item.Switch_Profile }}"
      state: query
    with_items: "{{ spreadsheet_Activate_Int_Profile }}"
    no_log: True
    register: interface_output

  - name: Json Query
    set_fact:
     query_result: "{{ interface_output | json_query('results[*].current[*].infraRsAccPortP.attributes.tDn')}}"
