---
- name: Get AP
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../../ACI_Deployment_Template.xlsx
    no_log: True

  - name: Get Application Profiles
    aci_ap:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.Tenant }}"
      ap: "{{ item.AP }}"
      state: query
    with_items: "{{ spreadsheet_Tenant_AP_EPG }}"
    no_log: True
    register: ap_output

  - name: Json Query
    set_fact:
      query_result: "{{ ap_output | json_query('results[*].current[*].fvAp.attributes.name')  }}"
