---
- name: Get CDP Policy
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../../ACI_Deployment_Template.xlsx
    no_log: True

  - name: Get new CDP policy
    aci_interface_policy_cdp:
      host: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: "{{ password }}"
      validate_certs: no
      cdp_policy: '{{ item.CDP_Policy }}'
      description: '{{ item.CDP_Description }}'
      admin_state: '{{ item.CDP_State }}'
      state: query
    with_items: "{{ spreadsheet_CDP_Policy}}"
    no_log: True
    register: cdp_output

  - name: Json Query
    set_fact:
      query_result: "{{ cdp_output | json_query('results[*].invocation.module_args.cdp_policy')}}"
