---
- name: Get L2 Interface Policy
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../../ACI_Deployment_Template.xlsx
    no_log: True

  - name: Get l2 interface policy
    aci_interface_policy_l2:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      l2_policy: '{{ item.L2_Interface }}'
      vlan_scope: '{{ item.VLAN_Scope }}'
      description: '{{ item.L2_Description }}'
      state: query
    with_items: "{{ spreadsheet_L2_Interface_Policy}}"
    no_log: True
    register: l2_output

  - name: Json Query
    set_fact:
     query_result: "{{ l2_output | json_query('results[*].current[*].l2IfPol.attributes.name')}}"
