---
- name: Get Switch vPC Pairs
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../../ACI_Deployment_Template.xlsx
    no_log: True

  - name: Get vPC Group
    aci_switch_policy_vpc_protection_group:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      protection_group: "{{ item.vPC_Explicit_Protection_Group }}"
      protection_group_id: "{{ item.vPC_Domain_ID }}"
      switch_1_id: "{{ item.Switch_1 }}"
      switch_2_id: "{{ item.Switch_2 }}"
      state: query
    with_items: "{{ spreadsheet_vPC_Protection_Gr }}"
    no_log: True
    register: vPC_output

  - name: Json Query
    set_fact:
      query_result: "{{ vPC_output | json_query('results[*].current[*].fabricExplicitGEp.attributes.name')}}"
