---
- name: Configure EPGs and Contracts
  hosts: apic
  connection: local
  gather_facts: no

  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../ACI_Deployment_Template.xlsx

  - name: Add/Delete a EPG
    aci_epg:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.Tenant }}"
      ap: "{{ item.AP }}"
      epg: "{{ item.EPG }}"
      bd: "{{ item.BD }}"
      state: "{{ item.State }}"
    with_items: "{{ spreadsheet_Tenant_AP_EPG }}"

  - name: Add/Delete a contract
    aci_contract:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.Tenant }}"
      contract: "{{ item.Contract }}"
      state: "{{ item.State }}"
    with_items: "{{ spreadsheet_Tenant_AP_EPG }}"

  - name: Add/Delete a contract to epg binding
    aci_epg_to_contract:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.Tenant }}"
      ap: "{{ item.AP }}"
      epg: "{{ item.EPG }}"
      contract: "{{ item.Contract }}"
      contract_type: "{{ item.Contract_Type }}"
      state: "{{ item.State }}"
    with_items: "{{ spreadsheet_Tenant_AP_EPG }}"

  - name: Add/Delete a epg domain binding for physical domain
    aci_epg_to_domain:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.Tenant }}"
      ap: "{{ item.AP }}"
      epg: "{{ item.EPG }}"
      domain: "{{ item.Domain }}"
      domain_type: "{{ item.Domain_Type }}"
      state: "{{ item.State }}"
    when: item.Domain_Type != "vmm"
    with_items: "{{ spreadsheet_Tenant_AP_EPG }}"

  - name: Add a new epg domain binding for vmm domain
    aci_epg_to_domain:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.Tenant }}"
      ap: "{{ item.AP }}"
      epg: "{{ item.EPG }}"
      domain: "{{ item.Domain }}"
      domain_type: "{{ item.Domain_Type }}"
      vm_provider: "{{ item.VM_Provider }}"
      state: "{{ item.State }}"
    when: item.Domain_Type == "vmm"
    with_items: "{{ spreadsheet_Tenant_AP_EPG }}"
