---
- name: Cisco SDWAN
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    templatename: []
    templateid: []
  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../SDWAN_Deployment_Template.xlsx
    no_log: true

  - name: Authentication
    uri:
      url: https://{{ host_ip }}:443/j_security_check
      method: 'POST'
      validate_certs: no
      headers:
        Accept: 'application/json'
      return_content: yes
      body_format: form-urlencoded
      body:
        j_username: "{{ username }}"
        j_password: "{{ password }}"
    no_log: true
    register: auth_output

  - name: Set fact token
    set_fact:
      cookie: "{{auth_output.cookies_string }}"
    no_log: true

  - name: Create Feature Template - AAA
    uri:
      url: https://{{ host_ip }}:443/dataservice/template/feature
      method: 'POST'
      validate_certs: no
      headers:
        Content-Type: 'application/json'
        Cookie: "{{ cookie }}"
      return_content: yes
      body_format: json
      # body: "{{ lookup('file', './templates/aaa.j2' ) }}"
      body: |
        {
          "deviceType": [
            "{{ item.Device_Model }}"
          ],
          "deviceModels": [
              {
                  "name": "{{ item.Device_Model }}",
                  "displayName": "{{ item.Display_Name }}",
                  "deviceType": "{{ item.Device_Type }}",
                  "isCliSupported": true,
                  "isCiscoDeviceModel": false
              }
          ],
          "feature": "vmanage-default",
          "factoryDefault": false,
          "templateName": "{{ item.Name }}",
          "templateDescription": "{{ item.Description }}",
          "templateType": "aaa",
          "templateMinVersion": "15.0.0",
          "templateDefinition": {
            "aaa": {
              "auth-order": {
                "vipType": "constant",
                "vipValue": [
                  {
                    "vipType": "constant",
                    "vipValue": "{{ item.Auth_Order1 }}",
                    "vipObjectType": "object"
                  },
                  {
                    "vipType": "constant",
                    "vipValue": "{{ item.Auth_Order2 }}",
                    "vipObjectType": "object"
                  },
                  {
                    "vipType": "constant",
                    "vipValue": "{{ item.Auth_Order3 }}",
                    "vipObjectType": "object"
                  }
                ],
                "vipObjectType": "list",
                "vipVariableName": "auth_order"
              },
              "auth-fallback": {
                "vipObjectType": "object",
                "vipType": "constant",
                "vipValue": "{{ item.Auth_Fallback }}",
                "vipVariableName": "auth_fallback"
              },
              "admin-auth-order": {
                "vipObjectType": "object",
                "vipType": "constant",
                "vipValue": "{{ item.Admin_Auth_Order }}",
                "vipVariableName": "admin_auth_order"
              },
              "logs": {
                "audit-disable": {
                  "vipObjectType": "object",
                  "vipType": "ignore",
                  "vipValue": true,
                  "vipVariableName": "disable_audit_logs"
                },
                "netconf-disable": {
                  "vipObjectType": "object",
                  "vipType": "ignore",
                  "vipValue": "true",
                  "vipVariableName": "disable_netconf_logs"
                }
              },
              "radius-servers": {
                "vipObjectType": "list",
                "vipType": "ignore",
                "vipValue": [
                  ""
                ],
                "vipVariableName": "radius_servers"
              },
              "usergroup": {
                "vipType": "constant",
                "vipValue": [
                  {
                    "name": {
                      "vipObjectType": "object",
                      "vipType": "constant",
                      "vipValue": "netadmin"
                    },
                    "viewMode": "view",
                    "priority-order": [
                      "name"
                    ]
                  },
                  {
                    "name": {
                      "vipObjectType": "object",
                      "vipType": "constant",
                      "vipValue": "basic"
                    },
                    "priority-order": [
                      "name",
                      "task"
                    ],
                    "task": {
                      "vipType": "constant",
                      "vipValue": [
                        {
                          "mode": {
                            "vipType": "constant",
                            "vipValue": "system",
                            "vipObjectType": "object"
                          },
                          "permission": {
                            "vipType": "constant",
                            "vipValue": [
                              {
                                "vipType": "constant",
                                "vipValue": "read",
                                "vipObjectType": "object"
                              },
                              {
                                "vipType": "constant",
                                "vipValue": "write",
                                "vipObjectType": "object"
                              }
                            ],
                            "vipObjectType": "list"
                          },
                          "priority-order": [
                            "mode",
                            "permission"
                          ]
                        },
                        {
                          "mode": {
                            "vipType": "constant",
                            "vipValue": "interface",
                            "vipObjectType": "object"
                          },
                          "permission": {
                            "vipType": "constant",
                            "vipValue": [
                              {
                                "vipType": "constant",
                                "vipValue": "read",
                                "vipObjectType": "object"
                              },
                              {
                                "vipType": "constant",
                                "vipValue": "write",
                                "vipObjectType": "object"
                              }
                            ],
                            "vipObjectType": "list"
                          },
                          "priority-order": [
                            "mode",
                            "permission"
                          ]
                        }
                      ],
                      "vipObjectType": "tree",
                      "vipPrimaryKey": [
                        "mode"
                      ]
                    }
                  },
                  {
                    "name": {
                      "vipObjectType": "object",
                      "vipType": "constant",
                      "vipValue": "operator"
                    },
                    "priority-order": [
                      "name",
                      "task"
                    ],
                    "task": {
                      "vipType": "constant",
                      "vipValue": [
                        {
                          "mode": {
                            "vipType": "constant",
                            "vipValue": "system",
                            "vipObjectType": "object"
                          },
                          "permission": {
                            "vipType": "constant",
                            "vipValue": [
                              {
                                "vipType": "constant",
                                "vipValue": "read",
                                "vipObjectType": "object"
                              }
                            ],
                            "vipObjectType": "list"
                          },
                          "priority-order": [
                            "mode",
                            "permission"
                          ]
                        },
                        {
                          "mode": {
                            "vipType": "constant",
                            "vipValue": "interface",
                            "vipObjectType": "object"
                          },
                          "permission": {
                            "vipType": "constant",
                            "vipValue": [
                              {
                                "vipType": "constant",
                                "vipValue": "read",
                                "vipObjectType": "object"
                              }
                            ],
                            "vipObjectType": "list"
                          },
                          "priority-order": [
                            "mode",
                            "permission"
                          ]
                        },
                        {
                          "mode": {
                            "vipType": "constant",
                            "vipValue": "policy",
                            "vipObjectType": "object"
                          },
                          "permission": {
                            "vipType": "constant",
                            "vipValue": [
                              {
                                "vipType": "constant",
                                "vipValue": "read",
                                "vipObjectType": "object"
                              }
                            ],
                            "vipObjectType": "list"
                          },
                          "priority-order": [
                            "mode",
                            "permission"
                          ]
                        },
                        {
                          "mode": {
                            "vipType": "constant",
                            "vipValue": "routing",
                            "vipObjectType": "object"
                          },
                          "permission": {
                            "vipType": "constant",
                            "vipValue": [
                              {
                                "vipType": "constant",
                                "vipValue": "read",
                                "vipObjectType": "object"
                              }
                            ],
                            "vipObjectType": "list"
                          },
                          "priority-order": [
                            "mode",
                            "permission"
                          ]
                        },
                        {
                          "mode": {
                            "vipType": "constant",
                            "vipValue": "security",
                            "vipObjectType": "object"
                          },
                          "permission": {
                            "vipType": "constant",
                            "vipValue": [
                              {
                                "vipType": "constant",
                                "vipValue": "read",
                                "vipObjectType": "object"
                              }
                            ],
                            "vipObjectType": "list"
                          },
                          "priority-order": [
                            "mode",
                            "permission"
                          ]
                        }
                      ],
                      "vipObjectType": "tree",
                      "vipPrimaryKey": [
                        "mode"
                      ]
                    }
                  }
                ],
                "vipObjectType": "tree",
                "vipPrimaryKey": [
                  "name"
                ]
              },
              "user": {
                "vipType": "constant",
                "vipValue": [
                  {
                    "vipOptional": false,
                    "name": {
                      "vipObjectType": "object",
                      "vipType": "constant",
                      "vipValue": "{{ item.Local_User_Name }}",
                      "vipVariableName": "user_name_0"
                    },
                    "password": {
                      "vipObjectType": "object",
                      "vipType": "constant",
                      "vipValue": "{{ item.Local_User_Password }}"
                    },
                    "description": {
                      "vipObjectType": "object",
                      "vipType": "constant",
                      "vipValue": "{{ item.Local_User_Description }}"
                    },
                    "group": {
                      "vipType": "constant",
                      "vipValue": [ "{{ item.Local_User_Group }}" ],
                      "vipObjectType": "list"
                    },
                    "priority-order": [
                      "name",
                      "password",
                      "secret",
                      "description",
                      "group"
                    ]
                  }
                ],
                "vipObjectType": "tree",
                "vipPrimaryKey": [
                  "name"
                ]
              }
            },
            "tacacs": {
              "timeout": {
                "vipObjectType": "object",
                "vipType": "constant",
                "vipValue": 5,
                "vipVariableName": {{ item.TACACS_Timeout }},
              },
              "authentication": {
                "vipObjectType": "object",
                "vipType": "constant",
                "vipValue": "{{ item.TACACS_Auth }}",
                "vipVariableName": "tacacs_authentication"
              },
                "server": {
                    "vipType": "constant",
                    "vipValue": [
                        {
                            "address": {
                                "vipObjectType": "object",
                                "vipType": "constant",
                                "vipValue": "{{ item.TACACS_Server }}",
                                "vipVariableName": "tacacs_tacacs_address"
                            },
                            "auth-port": {
                                "vipObjectType": "object",
                                "vipType": "ignore",
                                "vipValue": 49,
                                "vipVariableName": "tacacs_tacacs_auth_port"
                            },
                            "secret-key": {
                                "vipObjectType": "object",
                                "vipType": "constant",
                                "vipValue": "{{ item.TACACS_Secret_Key }}",
                                "vipVariableName": "tacacs_tacacs_secret_key"
                            },
                            "vpn": {
                                "vipObjectType": "object",
                                "vipType": "constant",
                                "vipValue": {{ item.TACACS_Source_VPN }},
                                "vipVariableName": "tacacs_tacacs_vpn"
                            },
                            "source-interface": {
                                "vipObjectType": "object",
                                "vipType": "constant",
                                "vipValue": "{{ item.TACACS_Source_Interface }}",
                                "vipVariableName": "tacacs_tacacs_source_interface"
                            },
                            "key": {
                                "vipObjectType": "object",
                                "vipType": "ignore",
                                "vipVariableName": "tacacs_tacacs_key"
                            },
                            "secret-key": {
                                "vipObjectType": "object",
                                "vipType": "ignore",
                                "vipVariableName": "tacacs_tacacs_secret_key"
                            },
                            "priority": {
                                "vipObjectType": "object",
                                "vipType": "ignore",
                                "vipValue": 0,
                                "vipVariableName": "tacacs_tacacs_priority"
                            },
                            "priority-order": [
                                "address",
                                "auth-port",
                                "vpn",
                                "source-interface",
                                "key",
                                "secret-key",
                                "priority"
                            ]
                        }
                    ],
                    "vipObjectType": "tree",
                    "vipPrimaryKey": [
                        "address"
                    ]
                }
              },
            "radius": {
              "timeout": {
                "vipObjectType": "object",
                "vipType": "ignore",
                "vipValue": 5,
                "vipVariableName": "radius_timeout"
              },
              "retransmit": {
                "vipObjectType": "object",
                "vipType": "ignore",
                "vipValue": 3,
                "vipVariableName": "retransmit"
              }
            }
          }
        }
    when: item.State == "present"
    with_items: "{{ spreadsheet_AAA }}"
    register: output

  - name: Display output
    debug:
      msg: "{{ output | to_nice_json }}"
