---
- name: Cisco SDWAN
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    templatename: []
    templateid: []
  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../SDWAN_Deployment_Template.xlsx
    no_log: true
    tags: get

  - name: Authentication
    uri:
      url: https://{{ host_ip }}:443/j_security_check
      method: 'POST'
      validate_certs: no
      headers:
        Accept: 'application/json'
      return_content: yes
      body_format: form-urlencoded
      body:
        j_username: "{{ username }}"
        j_password: "{{ password }}"
    no_log: true
    register: auth_output

  - name: Set fact token
    set_fact:
      cookie: "{{auth_output.cookies_string }}"
    no_log: true

  - name: Setting State
    set_fact:
      to_remove: "OK"
    when: item.State == "absent"
    with_items: "{{ spreadsheet_Delete_Feature_Template }}"

  - name: Get Template ID
    uri:
      url: https://{{ host_ip }}:443/dataservice/template/feature
      method: 'GET'
      validate_certs: no
      headers:
        Accept: 'application/json'
        Cookie: "{{ cookie }}"
      return_content: yes
    no_log: true
    register: featuretemplate
    when: to_remove == "OK"

  - name: Mapping Template Name and Template ID
    set_fact:
      tnameid: "{{ tnameid | default ({}) | combine({ item.templateName : item.templateId }) }}"
    with_items:
      - "{{ featuretemplate | json_query('json.data[]') }}"
    no_log: true
    when: to_remove == "OK"

  - name: Appending Template Name from SpreedSheet to templatename list
    set_fact:
      templatename: "{{ templatename + [item.Name] }}"
    no_log: true
    when: item.State == "absent"
    with_items: "{{ spreadsheet_Delete_Feature_Template }}"
#    when: to_remove == "OK"

  - name: Filter Template ID
    set_fact: 
      f_tid: >-
        {%- set f_tid = []-%}
        {%- for key, value in tnameid.items() -%}
          {%- for i in templatename -%}
            {%- if i == key -%}
              {%- set _ = f_tid.append(value) -%}
            {%- endif -%}
          {%- endfor -%}
        {%- endfor -%}
        {{ f_tid }}
    when: to_remove == "OK"

  - name: Delete Feature Template 
    uri:
      url: https://{{ host_ip }}:443/dataservice/template/feature/{{ item }}
      method: DELETE
      validate_certs: no
      headers:
        Accept: 'application/json'
        Cookie: "{{ cookie }}"
      return_content: yes
    with_items: "{{ f_tid }}"
    when: to_remove == "OK"

