---
- name: Cisco SDWAN
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    templatename: []
    file_contents: "{{ lookup('file', './templates/ospf_interface_data.json') }}"
    # templateid: []
  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: SDWAN_Deployment_Template.xlsx
    no_log: true
    tags: get

  - name: Authentication
    uri:
      url: https://{{ host_ip }}:443/j_security_check
      method: 'POST'
      validate_certs: no
      headers:
        Accept: 'application/json'
      return_content: yes
      body_format: form-urlencoded
      body:
        j_username: "{{ username }}"
        j_password: "{{ password }}"
    no_log: true
    register: auth_output

  - name: Set fact token
    set_fact:
      cookie: "{{auth_output.cookies_string }}"
    no_log: true

  - name: Get Template ID
    uri:
      url: https://{{ host_ip }}:443/dataservice/template/feature
      method: 'GET'
      validate_certs: no
      headers:
        Accept: 'application/json'
        Cookie: "{{ cookie }}"
      return_content: yes
    no_log: true
    register: featuretemplate

  - name: Appending Template Name from SpreedSheet to templatename list
    set_fact:
      templatename: "{{ templatename + [item.Name] }}"
    no_log: true
    when: item.Name != None
    with_items: "{{ spreadsheet_OSPF_Interface }}"

  - name: Filter Template ID
    set_fact: 
      f_tid: >-
        {%- set f_tid = []-%}
        {%- for i in featuretemplate | json_query('json.data[]') -%}
          {%- for j in templatename -%}
            {%- if i.templateName == j -%}
              {%- set _ = f_tid.append(i) -%}
            {%- endif -%}
          {%- endfor -%}
        {%- endfor -%}
        {{ f_tid }}

  - name: Save output to a file
    copy: content="{{ f_tid | to_nice_json }}" dest="templates/ospf_int_output.json"

  - name: Prepare payload
    command: "python spreadsheet_parser.py SDWAN_Deployment_Template.xlsx OSPF_Interface"
    no_log: true

  - name: Update Feature Template - OSPF Area and Interfaces
    uri:
      url: https://{{ host_ip }}:443/dataservice/template/feature/{{ item.templateId }}
      method: 'PUT'
      validate_certs: no
      headers:
        Content-Type: 'application/json'
        Cookie: "{{ cookie }}"
      return_content: yes
      body_format: json
      body: "{{ item }}"
    with_items: "{{ file_contents }}"

