---
- name: Cisco SDWAN
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    file_contents: "{{ lookup('file', './templates/snmpv2_data.json') }}"
  tasks:
  - name: Parse excel and make json file
    command: "python spreadsheet_parser.py SDWAN_Deployment_Template.xlsx SNMPv2"
    no_log: true

  - name: Authentication
    uri:
      url: https://{{ host_ip }}:443/j_security_check
      method: 'POST'
      validate_certs: no
      headers:
        Accept: 'application/json'
      return_content: yes
      body_format: form-urlencoded
      body:
        j_username: "{{ username }}"
        j_password: "{{ password }}"
    no_log: true
    register: auth_output

  - name: Set fact token
    set_fact:
      cookie: "{{auth_output.cookies_string }}"
    no_log: true

  - name: Create Feature Template - SNMPv2
    uri:
      url: https://{{ host_ip }}:443/dataservice/template/feature
      method: 'POST'
      validate_certs: no
      headers:
        Content-Type: 'application/json'
        Cookie: "{{ cookie }}"
      return_content: yes
      body_format: json
      body: "{{ item }}"
    with_items: "{{ file_contents }}"
