- name: Setup Pool
  hosts: localhost
  connection: local
  gather_facts: no
  environment:
    F5_USER: "{{ username }}"
    F5_PASSWORD: "{{ password }}"
    F5_VALIDATE_CERTS: "no"


  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../F5_Deployment_Template.xlsx

  - name: set primary_server mgmt IP variable
    set_fact:
      primary_server: "{{ item.mgmt_ip }}"
    with_items: "{{ spreadsheet_Base_Configuration }}"
    when: item.primary_node  == "yes"

  - debug:
      msg: Primary Server mgmt IP is {{ primary_server }}

  - name: set secondary_server mgmt IP variable
    set_fact:
      secondary_server: "{{ item.mgmt_ip }}"
    with_items: "{{ spreadsheet_Base_Configuration }}"
    when: item.primary_node != "yes"

  - debug:
      msg: Secondary Server mgmt IP is {{ secondary_server }}


  - name: Create pools
    bigip_pool:
      name: "{{ item.pool_name }}"
      lb_method: "{{ item.lb_method }}"
      slow_ramp_time: "120"
      #monitor_type: "{{ item.monitor_type }}"
      monitors: "{{ item.monitors }}"
      state: "{{ item.state }}"
      provider:
        server: "{{ primary_server }}"
    delegate_to: localhost
    with_items: "{{ spreadsheet_LTM_Service }}"

  - name: Add nodes to pools
    bigip_pool_member:
      pool: "{{ item.pool_name }}"
      host: "{{ item.pool_member }}"
      port: "{{ item.pool_port }}"
      state: "{{ item.state }}"
      #description: "{{ item.description }}"
      provider:
        server: "{{ primary_server }}"
    delegate_to: localhost
    with_items: "{{ spreadsheet_LTM_Service }}"
