- name: Setup Syslog
  hosts: localhost
  connection: local
  gather_facts: no
  environment:
    F5_USER: "{{ username }}"
    F5_PASSWORD: "{{ password }}"
    F5_VALIDATE_CERTS: "no"


  tasks:
  - name: Get facts from XLSX file
    xls_to_facts:
      src: ../F5_Deployment_Template.xlsx

  - name: set primary_server mgmt IP variable
    set_fact:
      primary_server: "{{ item.mgmt_ip }}"
    with_items: "{{ spreadsheet_Base_Configuration }}"
    when: item.primary_node  == "yes"

  - debug:
      msg: Primary F5 mgmt IP is {{ primary_server }}

  - name: set secondary_server mgmt IP variable
    set_fact:
      secondary_server: "{{ item.mgmt_ip }}"
    with_items: "{{ spreadsheet_Base_Configuration }}"
    when: item.primary_node != "yes"

  - debug:
      msg: Secondary F5 mgmt IP is {{ secondary_server }}

  - name: Add a remote syslog server to log to {{ primary_server }} and {{ secondary_server }}
    bigip_remote_syslog:
      remote_host: "{{ item[1].Syslog_Server_2}}"
      remote_port: "{{ item[1].Syslog_Server_Port }}"
#      remote_host: "{{ item[1].Syslog_Server_2 }}"
#      remote_port: "{{ item[1].Syslog_Server_Port }}"
      provider:
        password: "{{ password }}"
        server: "{{ item[0] }}"
        user: "{{ username }}"
    delegate_to: localhost
    with_nested:
      - [ "{{ primary_server }}", "{{ secondary_server }}" ]
      - "{{ spreadsheet_Banner_Syslog_NTP}}"
    ignore_errors: yes

  - name: Add a remote syslog server to log to {{ primary_server }} and {{ secondary_server }}
    bigip_remote_syslog:
#      remote_host: "{{ item[1].Syslog_Server_1}}"
#      remote_port: "{{ item[1].Syslog_Server_Port }}"
      remote_host: "{{item[1].Syslog_Server_1}}"
      remote_port: "{{item[1].Syslog_Server_Port}}"
      provider:
        password: "{{ password }}"
        server: "{{ item[0] }}"
        user: "{{ username }}"
    delegate_to: localhost
    with_nested:
      - [ "{{ primary_server }}", "{{ secondary_server }}" ]
      - "{{ spreadsheet_Banner_Syslog_NTP}}"
    ignore_errors: yes
