# Generated by Django 3.0.3 on 2020-03-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='Device_Templates',
        ),
    ]
