# Generated by Django 3.0.3 on 2020-03-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0002_auto_20200302_0926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device_Templates',
            new_name='Device_Template',
        ),
    ]
