# Generated by Django 3.0.3 on 2020-03-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0003_auto_20200302_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device_Template',
            new_name='DeviceTemplate',
        ),
        migrations.AlterModelOptions(
            name='devicetemplate',
            options={'verbose_name_plural': 'Device Templates'},
        ),
    ]
