# Generated by Django 3.0.3 on 2020-03-03 01:54

from django.db import migrations, models
import network_automation.models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0005_auto_20200302_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetemplate',
            name='template_File',
            field=models.FileField(storage=network_automation.models.OverwriteStorage(), upload_to='spreadsheets/'),
        ),
    ]
