# Generated by Django 3.0.3 on 2020-03-06 06:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0006_auto_20200303_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('action', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('results', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
            },
        ),
    ]
