# Generated by Django 3.0.3 on 2020-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0008_auto_20200306_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
