# Generated by Django 3.0.3 on 2020-03-09 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0009_auto_20200306_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='template_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
