# Generated by Django 3.0.3 on 2020-03-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0010_auditlogs_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlogs',
            name='email',
        ),
    ]
