# Generated by Django 3.0.3 on 2020-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0012_auto_20200309_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='template_path',
            field=models.CharField(default='/home/development/nucleus-django/network_automation/models.py', editable=False, max_length=5000),
        ),
    ]
