# Generated by Django 3.0.3 on 2020-03-19 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0013_auditlogs_template_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlogs',
            name='datetime',
        ),
        migrations.AddField(
            model_name='auditlogs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 19)),
        ),
        migrations.AddField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default=datetime.time(6, 50, 2, 595455)),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='results',
            field=models.TextField(),
        ),
    ]
