# Generated by Django 3.0.3 on 2020-03-20 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0014_auto_20200319_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlogs',
            name='template_path',
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 20)),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default=datetime.time(3, 38, 19, 113327)),
        ),
    ]
