# Generated by Django 3.0.3 on 2020-03-20 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0016_auto_20200320_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default=datetime.time(5, 10, 25, 104418)),
        ),
    ]
