# Generated by Django 3.0.3 on 2020-03-24 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0017_auto_20200320_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 24)),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='results',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default=datetime.time(7, 41, 0, 609739)),
        ),
    ]
