# Generated by Django 3.0.3 on 2020-03-24 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0018_auto_20200324_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='results',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default=datetime.time(8, 41, 0, 264942)),
        ),
    ]
