# Generated by Django 3.0.3 on 2020-03-24 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0019_auto_20200324_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlogs',
            old_name='results',
            new_name='result',
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default=datetime.time(9, 5, 48, 601646)),
        ),
    ]
