# Generated by Django 3.0.3 on 2020-03-24 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0020_auto_20200324_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default=datetime.time(9, 30, 47, 137431)),
        ),
    ]
