# Generated by Django 3.0.3 on 2020-03-24 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0021_auto_20200324_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default=datetime.time(11, 1, 20, 829479)),
        ),
    ]
