# Generated by Django 3.0.3 on 2020-03-25 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0022_auto_20200324_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 25)),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default='05:37 AM'),
        ),
    ]
