# Generated by Django 3.0.6 on 2020-08-05 04:57

import datetime
from django.db import migrations, models
import network_automation.models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0023_auto_20200325_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_Name', models.CharField(max_length=300)),
                ('inventory_File', models.FileField(storage=network_automation.models.OverwriteStorage(), upload_to='inventory/')),
            ],
            options={
                'verbose_name_plural': 'Inventory Files',
            },
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 5)),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default='04:57 AM'),
        ),
    ]
