# Generated by Django 3.0.6 on 2020-08-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0024_auto_20200805_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default='05:00 AM'),
        ),
    ]
