# Generated by Django 3.0.6 on 2021-07-05 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0025_auto_20200805_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 5)),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default='09:10 AM'),
        ),
    ]
