# Generated by Django 3.0.6 on 2021-07-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0026_auto_20210705_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='time',
            field=models.TimeField(default='09:21 AM'),
        ),
    ]
