[ios-routers]
192.168.245.17 ansible_ssh_user=cisco ansible_ssh_pass=cisco ansible_network_os=ios ansible_connection=network_cli ansible_become=yes ansible_become_method=enable ansible_become_pass=cisco

[ios-switches]
192.168.245.18 ansible_ssh_user=cisco ansible_ssh_pass=cisco ansible_network_os=ios ansible_connection=network_cli ansible_become=yes ansible_become_method=enable ansible_become_pass=cisco

[all:vars]
ansible_connection = local
